### ISSUE TITLE
Official Language of Australia

### ISSUE THREAD

**Issue by dawesi** [the-basetrip/country-information#3]
The official language of Australia under this standard is en-au English (Australian) which is as different from UK English as it is from US English.

this needs the secondary data for this standard attached to be useful for real-world use.

**Comment by svenkapudija** [comment]
So you are saying that instead of just differentiating by languages we should also specify the region(s)/locales eg. not just "English" but "UK English", "US English", "AU English" etc. in order to be more precise/useful for your use-case?
