### ISSUE TITLE
Currency and Dial Code Information

### ISSUE THREAD

**Issue by brunobertechini** [the-basetrip/country-information#4]
I believe the currency and dial code info for all countries will be a great add.

For Example for PANAMA: PA/PAN

```json

"currencies": [
   {  
      "alphaCode": "PAB",
      "numericCode": 590
   },
   {  
      "alphaCode": "USD",
      "numericCode": 840
   },
]
```

reference: http://www.nationsonline.org/oneworld/currencies.htm

...and Country Dial Code.

United States: 1
Brazil: 55
Switzerland: 41

**Comment by svenkapudija** [comment]
Country dial code is available in our commercial API plans so we will not include it in our free plan.
As for the currency, so instead of just using currency code as in "USD" which is ISO 4217 currency code, you are suggesting also numeric code as well?

As for the PA/PAN there is alpha2 and alpha3 code available in the current version for example for Panama it is
```
"code": {
  "alpha2": "PA",
  "alpha3": "PAN",
  "numeric": "591"
}
```

**Comment by brunobertechini** [comment]
Hello @svenkapudija 

> Country dial code is available in our commercial API plans so we will not include it in our free plan.
Thats okay.

> As for the currency, so instead of just using currency code as in "USD" which is ISO 4217 currency code, you are suggesting also numeric code as well?
Exacly. We have several apis that send us the numeric iso code instead of the string three letter

> As for the PA/PAN there is alpha2 and alpha3 code available in the current version for example for Panama it is
Regarding this, this is the country numeric code right? Not the currency one

Thanks a lot

**Comment by svenkapudija** [comment]
Oh I see. Will do it then the way I mentioned above with alpha2, alpha3 and numeric code for each currency.

**Comment by brunobertechini** [comment]
Awesome. Really appreciate. Thanks.

Regarding the sample code you posted:

```json
"code": {
  "alpha2": "PA",
  "alpha3": "PAN",
  "numeric": "591"
}
```

Is it already implemented on current version ? Or was it just a sample ?

I couldn't find it in the json file...
